# Generated by Django 3.1 on 2022-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('PVC_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('vote_ID', models.CharField(max_length=20)),
                ('vote_status', models.BooleanField()),
            ],
        ),
    ]
